### ISSUE TITLE
Road map

### ISSUE THREAD

**Issue by francisbrito** [francisbrito/react-native-contact-list-app#1]
- [ ] Add iOS support.
- [ ] Update contacts provider so contacts come from the device.
- [x] Write down usage, installation, etc docs.
- [ ] Write down lessons learned.
